name: design_tools
description: Package brings the design tools to your flutter app. It supports grid-lines and key-lines
version: 0.1.0
homepage: https://github.com/Ashok-Varma/design_tools

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.5.3
  test: ^1.16.8

flutter:
  uses-material-design: true

# pre-commit run --all-files
import_sorter:
  emojis: true # Optional, defaults to false
  comments: false # Optional, defaults to true